---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-tridentctl.html 
keywords: deploy, astra trident, methods, tridentctl 
summary: 'É possível implantar o Astra Trident usando `tridentctl`o .' 
---
= Implante com o tridentctl
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


É possível implantar o Astra Trident usando `tridentctl`o .


TIP: Se você ainda não se familiarizou com o link:../trident-concepts/intro.html["conceitos básicos"^], agora é um ótimo momento para fazer isso.


TIP: Para personalizar sua implantação, link:kubernetes-customize-deploy-tridentctl.html["aqui"^]consulte .

.O que você vai precisar
Para implantar o Astra Trident, os seguintes pré-requisitos devem ser atendidos:

* Você tem Privileges completo para um cluster compatível com Kubernetes.
* Você tem acesso a um sistema de storage NetApp compatível.
* Você tem a capacidade de montar volumes de todos os nós de trabalho do Kubernetes.
* Você tem um host Linux com `kubectl` (ou `oc`, se estiver usando o OpenShift) instalado e configurado para gerenciar o cluster do Kubernetes que deseja usar.
* Você definiu a `KUBECONFIG` variável de ambiente para apontar para a configuração do cluster do Kubernetes.
* Você ativou o link:requirements.html["Portas de recurso exigidas pelo Astra Trident"^].
* Se você estiver usando o Kubernetes com Docker Enterprise https://docs.docker.com/ee/ucp/user-access/cli/["Siga os passos para ativar o acesso CLI"^], .


Tem tudo isso? Ótimo! Vamos começar.


TIP: Para obter informações sobre como personalizar sua implantação, link:kubernetes-customize-deploy-tridentctl.html["aqui"^]consulte .



== Etapa 1: Qualifique seu cluster Kubernetes

A primeira coisa que você precisa fazer é fazer login no host Linux e verificar se ele está gerenciando um _working_, link:requirements.html["Cluster compatível com Kubernetes"^] que você tem o Privileges necessário para.


NOTE: Com o OpenShift, você usa `oc` em vez de `kubectl` em todos os exemplos que se seguem, e você deve fazer login como *system:admin* primeiro executando `oc login -u system:admin` ou `oc login -u kube-admin`.

Para verificar a versão do Kubernetes, execute o seguinte comando:

[listing]
----
kubectl version
----
Para ver se você tem o administrador do cluster do Kubernetes Privileges, execute o seguinte comando:

[listing]
----
kubectl auth can-i '*' '*' --all-namespaces
----
Para verificar se você pode iniciar um pod que usa uma imagem do Docker Hub e alcançar seu sistema de armazenamento pela rede de pod, execute o seguinte comando:

[listing]
----
kubectl run -i --tty ping --image=busybox --restart=Never --rm -- \
  ping <management IP>
----
Identifique a versão do servidor Kubernetes. Você o usará quando instalar o Astra Trident.



== Passo 2: Baixe e extraia o instalador


NOTE: O instalador do Trident cria um pod Trident, configura os objetos CRD que são usados para manter seu estado e inicializa os sidecars CSI que executam ações, como provisionar e anexar volumes aos hosts do cluster.

Você pode baixar e extrair a versão mais recente do pacote de instalação do Trident link:https://github.com/NetApp/trident/releases/latest["A seção _assets_ no GitHub"^]do .

Por exemplo, se a versão mais recente for 21.07.1:

[listing]
----
wget https://github.com/NetApp/trident/releases/download/v21.07.1/trident-installer-21.07.1.tar.gz
tar -xf trident-installer-21.07.1.tar.gz
cd trident-installer
----


== Etapa 3: Instale o Astra Trident

Instale o Astra Trident no namespace desejado executando o `tridentctl install` comando.

[listing]
----
./tridentctl install -n trident
....
INFO Starting Trident installation.                namespace=trident
INFO Created service account.
INFO Created cluster role.
INFO Created cluster role binding.
INFO Added finalizers to custom resource definitions.
INFO Created Trident service.
INFO Created Trident secret.
INFO Created Trident deployment.
INFO Created Trident daemonset.
INFO Waiting for Trident pod to start.
INFO Trident pod started.                          namespace=trident pod=trident-csi-679648bd45-cv2mx
INFO Waiting for Trident REST interface.
INFO Trident REST interface is up.                 version=21.07.1
INFO Trident installation succeeded.
....
----
Será assim quando o instalador estiver completo. Dependendo do número de nós no cluster do Kubernetes, é possível observar mais pods:

[listing]
----
kubectl get pod -n trident
NAME                           READY   STATUS    RESTARTS   AGE
trident-csi-679648bd45-cv2mx   4/4     Running   0          5m29s
trident-csi-vgc8n              2/2     Running   0          5m29s

./tridentctl -n trident version
+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 21.07.1        | 21.07.1        |
+----------------+----------------+
----
Se você vir saída semelhante ao exemplo acima, concluiu esta etapa, mas o Astra Trident ainda não está totalmente configurado. Vá em frente e continue para o próximo passo. link:kubernetes-postdeployment.html["tarefas pós-implantação"^]Consulte .

No entanto, se o instalador não for concluído com êxito ou se você não vir um *Running* `trident-csi-<generated id>`, a plataforma não foi instalada.


TIP: Para solucionar problemas durante a implantação, consulte link:../troubleshooting.html["solução de problemas"^] a seção.
